### ISSUE TITLE
change-password?

### ISSUE THREAD

**Issue by lgarron** [protocol-registries/well-known-uris#1]
* URI suffix: `change-password`
* Requested Change(s): Include?
* Your relationship to the original registrant: None.

I've been wondering, should `/.well-known/change-password` be registered?
There's a spec for it (https://wicg.github.io/change-password-url/), and I believe many sites already support it.

(It's always struck me as a bit weird that `change-password` was defined before e.g. `login`, but here we are.)

**Comment by mnot** [comment]
I'd prefer the request be from @hober directly, as she knows the status of the spec. Tess, what you want to do?

**Comment by hober** [comment]
Hi Mark! I've been holding off sending a registration request until we move the spec from WICG to WebAppSec, which should be happening Soon™. (See https://github.com/WICG/change-password-url/issues/18#issuecomment-623692131 for more.)

Has the registration process changed to filing issues in this repository? This is the first I've seen this repo, I think.

**Comment by mnot** [comment]
Hey Tess,

Yep, this is an approved™️ way to make a registration request. Happy to wait until you're ready.

Cheers,

**Comment by mnot** [comment]
Overtaken by #12
