### ISSUE TITLE
Suffix "enterprise-transport-security" is registered, but the reference uses "ets"

### ISSUE THREAD

**Issue by unor** [protocol-registries/well-known-uris#10]
* URI suffix: enterprise-transport-security
* Requested Change(s): use the same suffix in registry and reference
* Your relationship to the original registrant: none

In the [registry](https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml), the suffix `enterprise-transport-security` has this reference: [ETSI TS 103 523-3 clause 4.3.8.3](https://www.etsi.org/deliver/etsi_ts/103500_103599/10352303/01.02.01_60/ts_10352303v010201p.pdf) (PDF)

In this PDF, all examples use the suffix `ets` instead of `enterprise-transport-security`. The PDF doesn’t even seem to mention "enterprise-transport-security".

**Comment by mnot** [comment]
It appears that this reference is old; the most recent release of that standard is:
  https://www.etsi.org/deliver/etsi_ts/103500_103599/10352303/01.03.01_60/ts_10352303v010301p.pdf

I'll ask IANA to update it.
