### ISSUE TITLE
Registration Request: tor-relay

### ISSUE THREAD

**Issue by nusenu** [protocol-registries/well-known-uris#11]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

Enter the details of the link relation type below:

* URI suffix: tor-relay
* Change controller:  tor-dev AT lists.torproject.org
* Specification document(s): https://gitlab.torproject.org/tpo/core/torspec/-/blob/master/proposals/326-tor-relay-well-known-uri-rfc8615.md (this URI is static and will not change over time since the tor internal spec number has been assigned)

This replaces #8 and addresses @mnot 's previous concerns (spec is now located at torproject.org and the torproject is listed as change controller).

**Comment by mnot** [comment]
Requesting registration from IANA as provisional.

**Comment by nusenu** [comment]
Thanks. One minor nit: 

The change controller contact is a bit confusing when looking at
https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml

so I removed the obfuscation:
https://gitlab.torproject.org/tpo/core/torspec/-/commit/df41296bb227ee8acf59a1a6c7b9b48228210c09

to make it clearer:
https://gitlab.torproject.org/tpo/core/torspec/-/blob/master/proposals/326-tor-relay-well-known-uri-rfc8615.md#change-controller

Could you ask IANA to update the registry? Thanks!
