### ISSUE TITLE
'oslc' permanent suffix registration request

### ISSUE THREAD

**Issue by berezovskyi** [protocol-registries/well-known-uris#15]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

Enter the details of the link relation type below:

* URI suffix: `oslc`
* Change controller:  OASIS Open Services for Lifecycle Collaboration (OSLC) Open Project (OP) Project Governing Board (PGB) oslc-op-pgb@lists.oasis-open-projects.org. See also https://open-services.net/about/
* Specification document(s): https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/oslc-core.html (stable version that reached Project Specification stage, see below)
* Requested status: permanent

Any additional information (this will not be included in the registry)?

OSLC is a REST-based and [RDF-based](https://www.w3.org/TR/rdf11-primer/) standard that is in active industrial use since circa 2009. OSLC allows two main discovery mechanisms: through an RDF-based catalog and an XML "root services" document. If granted, this suffix would allow to remove the need for manual configuration of OSLC tools via supplying URIs to those documents exposed by other OSLC servers and replace it with an automated discovery at `/.well-known/oslc/rootservices.xml` etc.

The link above is to the stable spec version, the proposed change to the working draft that includes the  discovery mechanism using well-known URIs can be found here: https://github.com/oslc-op/oslc-specs/pull/456/files

**Comment by berezovskyi** [comment]
If you wish, we can change to status to provisional until the OSLC Core spec reaches the OASIS Standard status.

**Comment by berezovskyi** [comment]
Hello @mnot, do we need to submit this request also on the mailing list or apply for membership of some group?

**Comment by berezovskyi** [comment]
Just noticed on https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml that most change controllers are top-level orgs, we can change it to OASIS in case of our request https://www.oasis-open.org/

**Comment by mnot** [comment]
Hi @berezovskyi - sorry, I've been away. It's not necessary to do anything else, this is sufficient. 

If I understand the OASIS process and the documents status correctly, I think permanent registration is appropriate here -- that is, the document is considered final, even if it hasn't been elevated to a 'full standard' yet, correct?

Either change controller will suffice - what's your preference?

**Comment by berezovskyi** [comment]
Hello Mark,

Thank you for reviewing our application!

You are right, we are not expecting any significant changes other than the added section on the well-known URIs.

I don't expect any changes to this registration so having the top-level OASIS org as the change controller is fine.

Thank you again and wishing you a Merry Christmas and happy holidays!

–Andrew
