### ISSUE TITLE
Description of tags in the 'tag' URI scheme

### ISSUE THREAD

**Issue by IllidanS4** [protocol-registries/well-known-uris#16]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the link relation type below:

* URI suffix: tag
* Change controller: none
* Specification document(s): `https://github.com/protocol-registries/well-known-uris/issues/16`
* Requested status: permanent

[RFC 4151](https://tools.ietf.org/html/rfc4151) specifies a method for generating timestamped entities owned by individual authorities. The document however doesn't describe a way to query such an authority for a description of the specific portion of a tag, which is what this proposes (at least for the DNS section).

For a URI in the form of (RFC 4151) `"tag:" DNSname "," date ":" specific [ "#" fragment ]` (that is only for tags backed by the owner of a particular domain), the description of the tag would be available at `//DNSName/.well-known/tag/specific#fragment`. There are no restrictions on the form in which the description would be provided, if available (text, HTML, RDF etc.). It is recommended to include the full URI of the original tag in the description.

The intention is that it is the user who should verify (in any suitable way) that the current owner of the domain is the same as the one that issued the tag, if required. It is recommended to use an archiving service like web.archive.org, both by the user and the authority, so that the description of `tag:example.org,2020:thing` could be located at `https://web.archive.org/web/2020/http://example.org/.well-known/tag/thing`. Therefore in contrast to "real-time" services, the preferred way to provide and verify the description is via the archive.

**Comment by mnot** [comment]
This is not an appropriate reference.

**Comment by IllidanS4** [comment]
@mnot Is it sufficient to post the specification on another website, or are there some specific minimal requirements?

**Comment by mnot** [comment]
The link for 'requirements for registration' covers that pretty extensively, with some more information in the `README` of this repo.
