### ISSUE TITLE
Registration request for .well-known/rd (Resource Directory)

### ISSUE THREAD

**Issue by cabo** [protocol-registries/well-known-uris#17]
Please confirm that:

* [X] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [X] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [X] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the ~~link relation type~~ well-known URI below:

* URI suffix: rd
* Change controller:  IETF
* Specification document(s): https://datatracker.ietf.org/doc/draft-ietf-core-resource-directory/

* Status: permanent
* Related information: Details of the usage are in https://www.ietf.org/archive/id/draft-ietf-core-resource-directory-28.html#section-5.1

Any additional information (this will not be included in the registry)?

This registration is the result of an IETF standards-track process (approved document currently in RFC-editor queue).  The unusually short URI suffix was arrived at based on the specifics of the usage situation in constrained node networks, which strongly favor saving bytes.

**Comment by mnot** [comment]
Approved, noting that this is the result of an IETF consensus document as justification for allowing such a short name.
