### ISSUE TITLE
Well-known URI for application-specific purposes

### ISSUE THREAD

**Issue by Vroo** [protocol-registries/well-known-uris#18]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [ ] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the link relation type below:

* URI suffix: appspecific
* Change controller:  Bruce Leban
* Specification document(s): https://github.com/Vroo/well-known-uri-appspecific/blob/main/well-known-uri-for-application-specific-purposes.txt

Any additional information (this will not be included in the registry)?

**Comment by mnot** [comment]
'application' is a very generic term that's widely used already. If you'd like to provisionally register before it's adopted by a standards body, you should use something more specific, e.g., 'leban-application'. 

Also, I need to consult as to whether a google doc is acceptable as a stable reference.

**Comment by Vroo** [comment]
Thank you @mnot. I am trying to use a generic term as this is intended to be used by any application. I am open to a better name, but not one that puts my name in it. Since the motivating use case is verification, what do you think of 'verification' or 'appverification'?

I don't have a more stable place to put the doc but am willing to move it someplace more stable.

**Comment by Vroo** [comment]
I have changed the title to make it more clear what the intent is here and added this paragraph at the top of the background section:

All of the currently registered well-known URI suffixes are related to specific protocols or specifically define how the URIs are to be used. None provide a mechanism where an application can use a well-known URI for application-specific purposes without registering a new suffix. This proposal addresses that by designating a suffix for this purpose and providing naming rules that give each application distinct paths.

**Comment by mnot** [comment]
Something like 'appverification' would be better.

**Comment by Vroo** [comment]
I'm willing to change the suffix to appverification. I can move the document to a more stable location if you can tell me what qualifies as more stable. What are next steps @mnot ?

**Comment by mnot** [comment]
Sorry for the delay; I'm waiting for guidance on what's considered a stable reference.

**Comment by Vroo** [comment]
Also considering `appspecific` as the prefix name.

**Comment by mnot** [comment]
`appspecific` is good.

Could you put it into a GitHub repo?

**Comment by mnot** [comment]
Also, I notice you have an IETF Trust copyright on the document. IANAL, but the usual process for such documents is that they're submitted as Internet-Drafts. If you're not going to do that, it might be better to remove that notice, to avoid confusion.

**Comment by Vroo** [comment]
Posted to https://github.com/Vroo/well-known-uri-appspecific/blob/main/well-known-uri-for-application-specific-purposes.txt

**Comment by mnot** [comment]
I've edited the registration template above and forwarded to IANA; it should be registered soon. Thanks for your patience.
