### ISSUE TITLE
gpc.json

### ISSUE THREAD

**Issue by darobin** [protocol-registries/well-known-uris#21]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [ ] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the well-known URI below:

* URI suffix: gpc.json
* Change controller: Global Privacy Control project
* Specification document(s): https://globalprivacycontrol.github.io/gpc-spec/
* Status: provisional

Any additional information (this will not be included in the registry)?

The document will certainly be moved as the specification moves through the adoption process and the ownership will be transferred to W3C at some point. However, the specification is implemented by several browsers and high-profile web sites, so it feels like registering it sooner rather than later is best.

**Comment by mnot** [comment]
That makes sense. Please keep us informed of any changes in the spec URL.

**Comment by darobin** [comment]
Will do, thanks!

**Comment by TimvdLippe** [comment]
FYI https://globalprivacycontrol.github.io/gpc-spec/ no longer exists
