### ISSUE TITLE
Registration request: /.well-known/traffic-advice

### ISSUE THREAD

**Issue by jeremyroman** [protocol-registries/well-known-uris#22]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [ ] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

The current draft proposal is developed under an individual Google employee's account, because that is where the primary known user (private prefetch proxies) is documented. If necessary it could be moved elsewhere, likely into WICG/nav-speculation.

If so, please enter the details of the well-known URI below:

* URI suffix: traffic-advice
* Change controller: The editor(s) of the below linked document, pending a standards venue
* Specification document(s): https://buettner.github.io/private-prefetch-proxy/traffic-advice.html

Any additional information (this will not be included in the registry)?

**Comment by mnot** [comment]
Thank you. I'll request the change controller to be 'Jeremy Roman <jbroman@chromium.org>'. This will be registered provisionally until it's in a more formal venue.
