### ISSUE TITLE
webweaver.json

### ISSUE THREAD

**Issue by digionline-gmbh** [protocol-registries/well-known-uris#23]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the well-known URI below:

* URI suffix: webweaver.json
* Change controller:  DigiOnline GmbH, www.digionline.de, IANA Enterprise Number 17596
* Specification document(s): None. Simple JSON.

Any additional information (this will not be included in the registry)?
The URL is used to provide Apps the necessary JSONRPC- and SOAP-Endpoints (starting from the Domain of an e-mail address)
Example: https://www.digionline.de/.well-known/webweaver.json

Thanks!

**Comment by mnot** [comment]
Some form of specification document is required. 

Also, if this resource is specific to your product, a more precise name would be appropriate -- e.g., `digionline-webweaver`.

**Comment by mnot** [comment]
(a specification document could be on your web site, especially if it's specific to your product)

**Comment by digionline-gmbh** [comment]
Hi,

thanks for your fast reaction.

I have oriented myself at https://sshfp.github.io/sshfp.html.

So our specification document is located here:
https://www.webweaver.de/well-known

We already use the URI suffix webweaver.json in production.
And WebWeaver is ® for more than 20 year.
So we would like to continue with webweaver.json.

Thanks and bye,
Thomas
