### ISSUE TITLE
wot

### ISSUE THREAD

**Issue by mnot** [protocol-registries/well-known-uris#24]
If so, please enter the details of the well-known URI below:

* URI suffix: `wot`
* Change controller:  Michael McCool ([michael.mccool@intel.com](mailto:michael.mccool@intel.com)), Kazuyuki Ashimura ([ashimura@w3.org](mailto:ashimura@w3.org)), or [team-wot@w3.org](mailto:team-wot@w3.org)
* Specification document(s): Media Type of resource is defined here: Web of Things (WoT) Thing Description 1.1 (https://www.w3.org/TR/wot-thing-description11/ ) and will be application/td+jsonld (see section 12.1) or (for compatibility reasons) application/json (see section 7.2 of the WoT Discovery specification)

Any additional information (this will not be included in the registry)?

**Comment by mnot** [comment]
Two questions:

- Usually, registrations by standards organisations only nominate an organisational address for the change controller. Is it OK to just list team-wot@w3.org?
- For the spec documents, we don't need the media type registrations, just the definition of the resources' semantics. I don't see any reference to it in the linked document; could you please add relevant text?

**Comment by mmccool** [comment]
1. Yes, [team-wot@w3.org](mailto:team-wot@w3.org) is fine as the change controller.
2. The semantics are defined in https://www.w3.org/TR/wot-discovery/.  
Given this, I suggest we update the text as follows:
```
URI suffix: wot
Change controller: [team-wot@w3.org](mailto:team-wot@w3.org)
Specification document(s): See the WoT Discovery specification (https://www.w3.org/TR/wot-discovery/#introduction-well-known)
```
