### ISSUE TITLE
protocol-handler

### ISSUE THREAD

**Issue by SoniEx2** [protocol-registries/well-known-uris#25]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the well-known URI below:

* URI suffix: protocol-handler
* Change controller: Fedi-To https://fedi-to.net/
* Specification document(s): https://github.com/fedi-to/fedi-to.github.io/blob/main/protocol-handler.md

Any additional information (this will not be included in the registry)?

There's not really anything about it that makes it specific to Fedi-To; if other folks want to use it, they *should*. https://github.com/fedi-to/fedi-to.github.io/blob/main/design.md provides some additional details on design choices around this specification (as well as some quirks of Fedi-To), but they're not required by the main specification.

**Comment by mnot** [comment]
Hi,

This is a very generic name for a specific service (fedi-to). I'd suggest somethign like `fedi-to-handler` or just `fedi-to`. There's not enough specification or community update to specify it for generic use.

**Comment by SoniEx2** [comment]
fedi-to exists as a hack because WHATWG moves too slowly to spec a new design for protocol handlers. they're not specific to fedi-to.

**Comment by SoniEx2** [comment]
we've made an attempt to make the specification (far?) more generic. hope this helps.

**Comment by mnot** [comment]
Again, generic, broadly usable terms are priviledged by the registry; to consume them, we need to see some sort of community adoption / agreement. Unilaterally registering because the standards process is to slow for you isn't a good justification -- that would open the registry to squatting on popular / useful terms.

**Comment by SoniEx2** [comment]
wouldn't it be better to register it so other ppl can find out how to use it, than to get ppl to use it without registering it?

(either works for us but :shrug: )

**Comment by SoniEx2** [comment]
we would like to re-submit this so mastodon can use it for remote interactions
