### ISSUE TITLE
Registring URI to well known-did

### ISSUE THREAD

**Issue by sheetakshi** [protocol-registries/well-known-uris#27]
Please confirm that:

* [ ] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [ ] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [ ] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the well-known URI below:

* URI suffix: https://mspengg.com
* Change controller:  https://mspengg.com/.well-known/did.json
* Specification document(s): [
![Screenshot (96)](https://user-images.githubusercontent.com/81159266/215400931-f2257ee3-7419-4ed7-a343-dcf06fe9c9ec.png)
](url)

Any additional information (this will not be included in the registry)?

**Comment by mnot** [comment]
This isn't valid, and is isn't necessary to register a did.json file for your specific server.
