### ISSUE TITLE
Requesting registration for `/.well-known/did.json`

### ISSUE THREAD

**Issue by OR13** [protocol-registries/well-known-uris#28]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the well-known URI below:

* URI suffix: `/.well-known/did.json`
* Change controller:  public-credentials@w3.org
* Specification document(s): https://w3c-ccg.github.io/did-method-web/
* Status:  "provisional" (requested)

Any additional information (this will not be included in the registry)?

On behalf of the specification editors and W3C CCG, I am requesting a provisional registration.

I'm happy to be an individual point of contact, orie @ transmute . industries

**Comment by mnot** [comment]
I've requested registration. A URL in w3c.org space would be better; if you can get that please tell me when it's available (or just open a new issue) and we'll update accordingly. Thanks.
