### ISSUE TITLE
RFC 8615 registration request: "gender"

### ISSUE THREAD

**Issue by grothoff** [protocol-registries/well-known-uris#32]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the well-known URI below:

* URI suffix: gender
* Change controller:  hr@taler-systems.com
* Specification document(s):  https://erc.europa.eu/news/erc-2022-work-programme

Any additional information (this will not be included in the registry)?

The EU is requiring organizations receiving state funding to publish a gender equality plan. This registry entry will make it easy to automatically find and verify gender equality plans.  Note that the plan's content is for humans, so there is no technical specification and only the above legal requirement. 

See https://www.openaccessgovernment.org/gender-equality-plan/106176/
for a more compact description of the requirement (but less official) than the given specification.

Status should be provisional.

**Comment by mnot** [comment]
That's not a specification for a .well-known URI; it's a document expressing a very broad plan.

**Comment by grothoff** [comment]
The referenced document says that "Gender equality plans at host institutions. To be eligible for calls with deadlines in 2022, the institutions to host ERC grantees must have a gender equality plan or an equivalent strategic document in place at the time of the signing of the grant and for the duration of the project.". 

The main site linked includes a reference to 
https://ec.europa.eu/info/funding-tenders/opportunities/docs/2021-2027/horizon/wp-call/2022/wp_horizon-erc-2022_en.pdf where Annex 5 on page 74 goes into somewhat more details, if you are looking for the most strict definition of what a GEP is. I'm not sure if it is better to link to the PDF and/or how to reference Annex 5 properly.

The point of the registration entry is to standardize the location for a GEP that satisfies this legal requirement.

**Comment by Potherca** [comment]
I think that what @mnot means is something that isn't prose but machine-readable.

For instance, the Annex 5 you mentioned states:

> Annex 5
> ## Gender equality plans
> A gender equality plan of an Applicant Legal
>
> Entity must cover the following minimum process-related requirements:
>
> - Publication: formal document published on the institution’s website and signed by the top management
> - Dedicated resources: commitment of resources and gender expertise to implement it
> - Data collection and monitoring: sex/gender disaggregated data on personnel (and students for institutions concerned) and annual reporting based on indicators
> - Training: Awareness raising/trainings on gender equality and unconscious gender biases for staff and decision-makers
>
> Content-wise, recommended areas to be covered and addressed via concrete measures and targets are the following:
> - work-life balance and organisational culture
> - gender balance in leadership and decision-making
> - gender equality in recruitment and career progression
> - integration of the gender dimension into research and teaching content
> - measures against gender-based violence including sexual harassment.
>
> Other strategic documents such as a development plan, an inclusion strategy or a diversity strategy are considered as equivalent if they meet the requirements listed above.

So for a common digital format to exist, some authority needs to decide:

1. What information _specifically_ needs to be stated (required, optional, informative, normative, etc.)
2. Which format (TTL, JSON, YAML, CSV, whatever) they want the information to be in
3. Which channel(s) exist or need to be created in order for consumers and producers of such information to communicate which each other and the authority

Once all parties involved have come to a common understanding and created an official document that outlines these exact specifications, _then_ we could start thinking about a `.well-known/`.

Of course, this is just my personal opinion as I am in no way affiliated with... well, anything really. :wink:
