### ISSUE TITLE
Registration request: .well-known/knx

### ISSUE THREAD

**Issue by MeMichael151** [protocol-registries/well-known-uris#36]
*Please confirm that:*
* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

*If so, please enter the details of the well-known URI below:*
* URI suffix: .well-known/knx
* Change controller:  KNX Association, Joost Demarest (joost.demarest@knx.org)
* Specification document(s): See schema.knx.org

*Any additional information (this will not be included in the registry)?*
* .well-known/knx is specified in EN50090-6-3:2023 Clause 4.2.5.1.1

**Comment by mnot** [comment]
Registrations are required to have 'a permanent and readily available public specification' per RFC8126. Are you able to make this specification available without charging a fee?

**Comment by MeMichael151** [comment]
Dear @mnot, EN50090-6-3 is a publicly available standard. We quoted EN50090-6-3 in our application. Is that sufficient?

**Comment by mnot** [comment]
At what URL?

**Comment by MeMichael151** [comment]
[3_10_4 KNX IoT 3rd Party API.pdf](https://github.com/protocol-registries/well-known-uris/files/12320791/3_10_4.KNX.IoT.3rd.Party.API.pdf)

This consortium standard was the basis for the EN50090-6-3

**Comment by mnot** [comment]
It needs to be a stable, long-term URL, ideally by the publishing body, or in the case of CENELEC, one of the national bodies. From what I can see, they only make it available for a fee.

Can you host it at a public URL on knx.org?

**Comment by MeMichael151** [comment]
schema.knx.org is a public url. It is mentioned in the EN50090-6-3.

**Comment by mnot** [comment]
We need a public, stable URL for the specification. If you cannot provide one, we cannot register the value.

**Comment by MeMichael151** [comment]
Ok, understood. Give me a few days to make the KNX IoT Specifications available on schema.knx.org
I'll ping you when ready, ok?

**Comment by MeMichael151** [comment]
We just made the KNX IoT 3rd Party API public on schema.knx.org but here is a public, stable URL: [https://knxcloud.org/index.php/s/jdZXpCC3EolQgH2/download](url)

**Comment by MeMichael151** [comment]
It is here: [https://knxcvba.sharepoint.com/:b:/s/KNXPublic/ETODhqH45qZOq-eJqHZN5UkBYVZoFF0IDZHZh3i6wX-Z5Q?e=U4ohs0](https://knxcvba.sharepoint.com/:b:/s/KNXPublic/ETODhqH45qZOq-eJqHZN5UkBYVZoFF0IDZHZh3i6wX-Z5Q?e=U4ohs0) and still on [[schema.knx.org](https://schema.knx.org/)](https://schema.knx.org/)
