### ISSUE TITLE
Registration Request: mercure

### ISSUE THREAD

**Issue by dunglas** [protocol-registries/well-known-uris#4]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

Enter the details of the link relation type below:

* URI suffix: mercure
* Change controller:  Les-Tilleuls.coop
* Specification document(s): https://datatracker.ietf.org/doc/draft-dunglas-mercure/

Any additional information (this will not be included in the registry)?

The Mercure is already widely used (see the Implementation Status section of the I-D) and is already listed in the [List of /.well-known/ services offered by webservers](https://en.wikipedia.org/wiki/List_of_/.well-known/_services_offered_by_webservers) Wikipedia page.
I plan to propose this I-D as a RFC soon.

The registration of link relation type has also be started: https://github.com/protocol-registries/link-relations/issues/21

**Comment by mnot** [comment]
Hello,

The specification document you list is an Internet-Draft that isn't currently on any stream (IETF, IAB, Independent or IRTF), and as such isn't a suitable reference for registration. Once it's on a stream, it can be considered for provisional registration, becoming permanent when it's an RFC.

Thank you,

P.S. I note that the draft also uses `/.well-known/subscriptions`, which isn't registered. Was that intentional?

**Comment by dunglas** [comment]
> P.S. I note that the draft also uses /.well-known/subscriptions, which isn't registered. Was that intentional?

It was an issue in the spec. It's fixed now (the good URL is `/.well-known/mercure/subscription`. Thanks for reporting.

Regarding the stream, I'm not sure of how to fix this. I've sent you a mail about that (among other things).

**Comment by mnot** [comment]
Closing as the draft has long expired.

**Comment by dunglas** [comment]
@mnot we still maintain the draft on GitHub and the protocol is now widely used. To be honest I still don't understand very well how to get this protocol published by the IETF.

**Comment by mnot** [comment]
is the URL https://mercure.rocks/spec stable? If so, we can use that.

---

Re: publication in the IETF -- 

Briefly, there are three paths:

1. Get it adopted by a WG (or start one). In this case, it probably means holding a BoF
2. Get an Area Director to agree to sponsor it. They'll want to see community support
3. Get it onto the independent stream, which cannot produce standards; your RFC (if you get one) will be Informational.

For (1) or (2), your first step is likely [DISPATCH](https://wiki.ietf.org/group/dispatch); note that the IETF is meeting in a couple of weeks, so if you start this _now_ you might get onto the agenda (and you can participate remotely).

For (3), see [the instructions](https://www.rfc-editor.org/about/independent/).

**Comment by dunglas** [comment]
Yes it is!
