### ISSUE TITLE
Registration request: related-website-set.json

### ISSUE THREAD

**Issue by sjledoux** [protocol-registries/well-known-uris#40]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the well-known URI below:

* URI suffix: related-website-set.json
* Change controller:  Google Inc.
* Specification document(s): https://github.com/GoogleChrome/related-website-sets/blob/main/Well-Known-Specification.md

Any additional information (this will not be included in the registry)?

This document represents a JSON file that sites within Related Website Sets must maintain to demonstrate ownership. [Related Website Sets](https://wicg.github.io/first-party-sets/) is a web platform proposal that is under incubation in the W3C Web Incubator Community Group. The specification document is maintained as part of the GoogleChrome GitHub repository for Related Website Sets, and its location is expected to be stable.

**Comment by mnot** [comment]
It would be good to update your spec to indicate what URL scheme(s) the well-known location can be used with.

**Comment by sjledoux** [comment]
[The specification has now been updated](https://github.com/GoogleChrome/related-website-sets/blob/main/Well-Known-Specification.md#:~:text=Such%20sites%20must%20use%20the%20https%20scheme%20in%20order%20to%20participate%20in%20RWS%20and%20host%20this%20well%2Dknown%20file.) to say that the well-known can only be used with the `https` scheme.

**Comment by sjledoux** [comment]
Hi @mnot, I noticed that [well-known/related-website-set.json has been registered with IANA](https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml#:~:text=related%2Dwebsite%2Dset.json), but this issue is still open. Is there anything else we need to do in order to close it?

**Comment by mnot** [comment]
Nope - thanks!
