### ISSUE TITLE
Registration request: nostr.json

### ISSUE THREAD

**Issue by fishcakeday** [protocol-registries/well-known-uris#42]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the well-known URI below:

* URI suffix: nostr.json
* Change controller: Nostr Developer Community and @fiatjaf (the creator of the initial proposal) - https://github.com/nostr-protocol/nostr?tab=readme-ov-file
* Specification document(s): https://github.com/nostr-protocol/nips/blob/master/05.md

Any additional information (this will not be included in the registry)?

**Comment by mnot** [comment]
I'm going to register with "Nostr Developer Community" as the change controller, as sharing it is problematic.
