### ISSUE TITLE
/.well-known/ssf-configuration

### ISSUE THREAD

**Issue by FragLegs** [protocol-registries/well-known-uris#44]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the well-known URI below:

* URI suffix: ssf-configuration
* Change controller:  OpenID - Shared Signals Working Group
* Specification document(s): [https://openid.net/specs/openid-sharedsignals-framework-1_0-ID2.html](https://openid.net/specs/openid-sharedsignals-framework-1_0-ID2.html)

Any additional information (this will not be included in the registry)?

Please refer to [section 6.2 of the specification document](https://openid.net/specs/openid-sharedsignals-framework-1_0-ID2.html#section-6.2) for info on the well known endpoint for OpenID's Shared Signals Framework.

This document is currently in Implementer's Draft 2, but there are already a number of security vendors with production implementations. 

For additional questions, you can contact the mailing list by [signing up here](https://lists.openid.net/mailman/listinfo/openid-specs-risc) or send an email to one of the co-chairs, Shayne Miel (smiel@cisco.com) or Sean O'Dell (IAM@seanodentity.com).

More information about Shared Signals can be found on [OpenID's working group page](https://openid.net/wg/sharedsignals/).

**Comment by mnot** [comment]
Registering as provisional. Once the document is final, please say so and we'll update to permanent.

It'd be helpful to update the IANA considerations section of the document to cover this registration. Also, note that the correct reference for well-known URIs is now RFC8615.
