### ISSUE TITLE
​​The "tpcd/grace-period.json" Well-Known Resource Identifier

### ISSUE THREAD

**Issue by njeunje** [protocol-registries/well-known-uris#46]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [ ] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.
    * This is managed by google.

If so, please enter the details of the well-known URI below:

* URI suffix: /tpcd/grace-period.json
* Change controller:  tpcd-mitigations-team@google.com
* Specification document(s): https://github.com/explainers-by-googlers/3pcd-grace-period-opt-out/blob/main/well-known-specification.md
* Status: Provisional
* Related information: https://github.com/explainers-by-googlers/3pcd-grace-period-opt-out

Any additional information (this will not be included in the registry)?

**Comment by mnot** [comment]
You need to register just 'tpcd' - that will put everything under `/.well-known/tpcd` under your control. If that makes sense I'll go ahead and request the provisional registration.

**Comment by njeunje** [comment]
Thanks, that makes sense and I'm okay with that.
