### ISSUE TITLE
No operation

### ISSUE THREAD

**Issue by Roy-Orbison** [protocol-registries/well-known-uris#47]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [ ] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the well-known URI below:

* URI suffix: `no-op`

Any additional information (this will not be included in the registry)?

Much like the [computer instruction][0], hence the namesake, there would be benefit from defining a URI that is explicitly intended to _not_ produce a full document nor be required to adhere to a particular information structure. This type of URI is very useful for assessing basic connectivity without triggering the cascade of typical processing, such as initiating & resuming browsing sessions via cookies, redirecting to canonical URIs, generating dynamic content, establishing database connections, conditional responses based on request headers, counting towards site analytics events, etc. The intention is to obviate the need for site operators and third party tools to invent their own URI, or at least the prefix. It would facilitate checks on whether a site exists and is reachable, optionally including its ability to negotiate TLS connections, without indicating participation in any system referenced by other Well-Known URIs.

As far as requirements go, returning _any_ HTTP response at all should be sufficient, though I imagine a reasonable baseline would be an empty plain text or HTML response, with a status in the 2XX or 5XX ranges. Whether a site wishes to respond via a static files or some level of dynamic generation depends on what its operator considers "available". Responses could be arbitrary and altered at the site's discretion, possibly based on additional path components or query string parameters.

In everyday use, it would be ideal for uptime monitors, SSL certificate validation, and point-to-point network connectivity tests, without placing undue load on the target server. Though HTTP requests are not required to validate certificates, programs like OpenSSL and publicly available services often perform them anyway. It would also serve as a consistent, recognisable string when reading or filtering logs.

[0]: https://en.wikipedia.org/wiki/NOP_(code)

**Comment by mnot** [comment]
Registrations require a stable reference. See also #13.

**Comment by Roy-Orbison** [comment]
I was hoping this would be simple and logical enough that IANA might want to provide said reference.
