### ISSUE TITLE
openid-federation

### ISSUE THREAD

**Issue by mnot** [protocol-registries/well-known-uris#49]
_filed on behalf of Mike Jones_

Please confirm that:

* [ ] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [ ] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [ ] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the well-known URI below:

·        URI suffix: openid-federation
·        Change controller: OpenID Foundation Artifact Binding Working Group - [openid-specs-ab@lists.openid.net](mailto:openid-specs-ab@lists.openid.net)
·        Specification document: Section 9 of OpenID Federation 1.0 - https://openid.net/specs/openid-federation-1_0.html#name-well-known-uri-registry
·        Related information: (none)

**Comment by mnot** [comment]
Questions:
* The document identifies its source as "OpenID Connect Working Group", but above the change controller is "OpenID Foundation Artifact Binding Working Group" - can you confirm the correct value?
* What state is this document in? It lists itself as draft, so I assume it is not final.

Also, this isn't blocking feedback, but you may want to consider specifying what URI scheme(s) the well-known URI is usable with.

**Comment by selfissued** [comment]
Yes, I confirm that:
> I have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
> I have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets my needs.
> The specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

Answers:

- The OpenID Connect Working Group is a newer name for the OpenID Artifact Binding Working Group.  They are one and the same thing - hence the title "AB/Connect Working Group" at https://openid.net/wg/connect/.  (This is more than you probably want to know, but the WG originally started working on an artifact binding (a la SAML2) for OpenID 2.0, but pivoted in the JSON/REST direction and instead created what became OpenID Connect.)  The existing registrations at https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml reference the "OpenID Foundation Artifact Binding Working Group", so we did the same in this request.
- This document is what's called an Implementer's Draft.  IPR from contributors is locked in and the reference is stable.  It's been reviewed by the full membership of the OpenID Foundation, as recorded at https://openid.net/fourth-implementers-draft-of-openid-federation-approved/ .  The working group decided to request registrations before taking the specification to Final status (probably later this year) in case any updates were requested by designated experts before the registrations occur.

Good point about specifying the URI scheme(s).  I'd thought we'd done that, but reviewing the doc, we may have not.  We definitely will specify that it's to only be used with "https", should the other editors agree with me that we failed to do so.
