### ISSUE TITLE
Open API Specification document

### ISSUE THREAD

**Issue by ehnsg** [protocol-registries/well-known-uris#51]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the well-known URI below:

* URI suffix: openapi.json
* Change controller: The OpenAPI Initiative, a Linux Foundation Collaborative Project
* Specification document(s): https://spec.openapis.org/oas/latest.html

Any additional information (this will not be included in the registry)?

* Information about the governance of the Open API Specification: https://www.openapis.org/participate/how-to-contribute/governance
* The specification reference URL is stable in the sense of always providing the _latest_ version. Specific links exist to each specific version: https://github.com/OAI/OpenAPI-Specification/tree/main/versions
* Each OpenAPI Document includes the version of the Open API Specification used, so the common usage is for servers to expose just one OpenAPI Document (i.e. NOT expose openapi_v2.json and openapi_v3.json individually) and let the clients figure out which spec version is observed using data inside the document.

**Comment by darrelmiller** [comment]
As one of the editors of the OpenAPI specification, I was not aware of this registration being made and do not support its registration in the current form.

**Comment by ehnsg** [comment]
Hi, @darrelmiller. Would you prefer it amended or retracted?

**Comment by ehnsg** [comment]
I would for sure prefer to work with you to figure out what you'd consider an acceptable registration, as there's a very real unmet standardization desire behind the request for a .well-known URI.

**Comment by mnot** [comment]
The path to doing that is engaging in the openapi community, not making a unilateral registration request. Closing.
