### ISSUE TITLE
/.well-known/casper/

### ISSUE THREAD

**Issue by johnwiard** [protocol-registries/well-known-uris#53]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the well-known URI below:

* URI suffix: /.well-known/casper/
* Change controller:  IETF
* Specification document(s): https://www.johnwiardgroup.io.vn/

Any additional information (this will not be included in the registry)?

**Comment by mnot** [comment]
There is no specification, your web site tries to capture google credentials, and personal URLs are not considered stable.
