### ISSUE TITLE
request to register /.well-known/brski

### ISSUE THREAD

**Issue by mcr** [protocol-registries/well-known-uris#7]
Please confirm that:

* [X ] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [X ] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [X] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

Enter the details of the link relation type below:

* URI suffix: brski
* Change controller:  IESG
* Specification document(s): draft-ietf-anima-bootstrapping-keyinfra

Any additional information (this will not be included in the registry)?

WG is still discussing whether to make this change from /.well-known/est

**Comment by mcr** [comment]
Thread about this  https://mailarchive.ietf.org/arch/msg/anima/jjusQdqzS3G4WbczolCxF0_YmQQ/

**Comment by mnot** [comment]
Waiting for stable reference in [the document](https://datatracker.ietf.org/doc/draft-ietf-anima-bootstrapping-keyinfra/).

**Comment by mnot** [comment]
@mcr I just got the request through IANA for `brski` - can you confirm this is ready to go (normally I'd just go, but the history is a bit convoluted here).

**Comment by mcr** [comment]
> @mcr I just got the request through IANA for `brski` - can you confirm this is ready to go (normally I'd just go, but the history is a bit convoluted here).

It's stable, it went through a second IETF LC (ended last week).
