### ISSUE TITLE
Registration Request: tor-relay

### ISSUE THREAD

**Issue by nusenu** [protocol-registries/well-known-uris#8]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

Enter the details of the link relation type below:

* URI suffix: tor-relay
* Change controller:  tor-relay-well-known-uri AT riseup.net
* Specification document(s): https://nusenu.github.io/tor-relay-well-known-uri-spec/

Related thread on the tor-dev mailing list:
https://lists.torproject.org/pipermail/tor-dev/2020-July/014401.html
https://lists.torproject.org/pipermail/tor-dev/2020-August/014409.html

**Comment by nusenu** [comment]
After seeing the comments from  #2 I made sure the spec is accessible via github pages.

**Comment by mnot** [comment]
@nmathewson @mikeperry-tor any comment here? Given that it's prefixed by `tor-`, I'd *strongly* prefer the specification document to be published by Tor, not a third party.

**Comment by nusenu** [comment]
Nick Mathewson's reaction:
https://lists.torproject.org/pipermail/tor-dev/2020-August/014429.html

**Comment by mnot** [comment]
Thanks. 

Having a third party retain change control over something with a project's name as a prefix isn't optimal; it's easy to imagine that a disagreement down the line could lead to a bad situation. See [their trademark policy](https://www.torproject.org/about/trademark/). 

I can think of a number of ways to resolve this:
* A different name can be used (e.g., `riseup-tor-relay`) -- I understand that's probably not great
* The Tor project can be listed as the change controller in the registration
* We can get you on record as saying that you'll cede change control to them if they request it
* Something else you work out between you and Tor (e.g., it might be sufficient to make it clear in your specification that it isn't an official Tor product).

Thoughts? Sorry to be so pedantic about this.

**Comment by nmathewson** [comment]
I would be fine with either of these options, if they're good with you, nusenu:

> * The Tor project can be listed as the change controller in the registration
> * We can get you on record as saying that you'll cede change control to them if they request it

But I do have one question -- would it be better to have the URL be something like `.tor-relay` or `tor-relay-info`? I don't want to collide with anybody already using "tor-relay" on their sites already. (Sorry if this is already a solved problem.)

Also, I'm about to go on vacation, so I won't be around to take further action on this until mid-September. I hope the above will be enough information to work with.

**Comment by nusenu** [comment]
Hi @nmathewson,
I believe the easiest way to address Mark's concerns is to make the spec be located at tpo.
So I submitted it here for you to assign a tor proposal number: 
https://github.com/torproject/torspec/pull/129

Once you assigned it a proposal number (which results in a static URL) and it is in state accepted Mark's concerns should be dealt with. Would be great if you could do that before leaving for vacation.

Also note the change in the "Change Controller" - which I set to the tor-dev mailing list in that PR linked above.

The url will be "example.com/.well-known/tor-relay/..."
so we do not collide with "example.com/tor-relay/".

**Comment by nusenu** [comment]
replaced by #11
