### ISSUE TITLE
trust.txt

### ISSUE THREAD

**Issue by scodtt** [protocol-registries/well-known-uris#9]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

Enter the details of the link relation type below:

* URI suffix: trust.txt
* Change controller: JournalList.net, a 501(c)6 non-profit member-owned cooperative.  
* Specification document(s): https://journallist.net/reference-document-for-trust-txt-specifications

Any additional information (this will not be included in the registry)?

**Comment by mnot** [comment]
Your specification uses `/trust.txt` in the root of the path, which is exactly what well-known URIs are defined to avoid. This is bad practice, for the reasons listed in the RFC.

If you intend to update the specification to use `/.well-known/trust.txt`, please say so.

**Comment by mnot** [comment]
OK. I'm flipping this to 'waiting for stable reference' until the specification is updated.

**Comment by brownwolf1355** [comment]
Scott asked that I let you know that the trust.txt specification has been stable since August, 2021.
